# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdaterGUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.setEnabled(True)
        Main.resize(954, 604)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/mainUpdater.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        self.label_hello = QtWidgets.QLabel(Main)
        self.label_hello.setGeometry(QtCore.QRect(280, 30, 400, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_hello.setFont(font)
        self.label_hello.setWhatsThis("")
        self.label_hello.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hello.setWordWrap(False)
        self.label_hello.setObjectName("label_hello")
        self.button_exit = QtWidgets.QPushButton(Main)
        self.button_exit.setGeometry(QtCore.QRect(870, 30, 51, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 69, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 69, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 69, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 69, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 69, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 69, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 69, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 69, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 69, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.button_exit.setPalette(palette)
        self.button_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_exit.setAutoFillBackground(False)
        self.button_exit.setStyleSheet("QPushButton{color: rgb(255, 255, 255)}\n"
"QPushButton{background-color: rgb(232, 69, 68)}\n"
"QPushButton:pressed{color: rgb(232, 69, 68)}\n"
"QPushButton:pressed{background-color: rgb(255, 255, 255)}\n"
"QPushButton{border-radius:10px}")
        self.button_exit.setCheckable(False)
        self.button_exit.setChecked(False)
        self.button_exit.setObjectName("button_exit")
        self.edit_search = QtWidgets.QLineEdit(Main)
        self.edit_search.setGeometry(QtCore.QRect(142, 74, 121, 21))
        self.edit_search.setStyleSheet("border-radius: 5px;\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(167, 167, 167);")
        self.edit_search.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edit_search.setInputMask("")
        self.edit_search.setText("")
        self.edit_search.setObjectName("edit_search")
        self.button_search = QtWidgets.QPushButton(Main)
        self.button_search.setGeometry(QtCore.QRect(270, 70, 61, 32))
        self.button_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_search.setObjectName("button_search")
        self.select_term = QtWidgets.QComboBox(Main)
        self.select_term.setGeometry(QtCore.QRect(20, 70, 101, 31))
        self.select_term.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_term.setObjectName("select_term")
        self.select_term.addItem("")
        self.select_term.addItem("")
        self.select_term.addItem("")
        self.select_term.addItem("")
        self.edit_path = QtWidgets.QLineEdit(Main)
        self.edit_path.setEnabled(False)
        self.edit_path.setGeometry(QtCore.QRect(440, 74, 261, 21))
        self.edit_path.setStyleSheet("border-radius: 5px;\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(167, 167, 167);")
        self.edit_path.setObjectName("edit_path")
        self.button_path = QtWidgets.QPushButton(Main)
        self.button_path.setGeometry(QtCore.QRect(710, 70, 91, 32))
        self.button_path.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_path.setObjectName("button_path")
        self.list_course = QtWidgets.QTableView(Main)
        self.list_course.setGeometry(QtCore.QRect(20, 140, 391, 441))
        self.list_course.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.list_course.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_course.setAlternatingRowColors(True)
        self.list_course.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.list_course.setShowGrid(False)
        self.list_course.setObjectName("list_course")
        self.list_course.horizontalHeader().setVisible(False)
        self.list_course.horizontalHeader().setCascadingSectionResizes(False)
        self.list_course.horizontalHeader().setDefaultSectionSize(0)
        self.list_course.horizontalHeader().setMinimumSectionSize(0)
        self.list_course.horizontalHeader().setStretchLastSection(True)
        self.list_course.verticalHeader().setVisible(False)
        self.list_course.verticalHeader().setHighlightSections(True)
        self.tree_update = QtWidgets.QTreeWidget(Main)
        self.tree_update.setGeometry(QtCore.QRect(410, 140, 391, 441))
        self.tree_update.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tree_update.setAlternatingRowColors(True)
        self.tree_update.setObjectName("tree_update")
        self.tree_update.headerItem().setText(0, "1")
        self.tree_update.header().setVisible(False)
        self.check_all = QtWidgets.QCheckBox(Main)
        self.check_all.setGeometry(QtCore.QRect(810, 140, 61, 20))
        self.check_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_all.setObjectName("check_all")
        self.label_course = QtWidgets.QLabel(Main)
        self.label_course.setGeometry(QtCore.QRect(20, 120, 221, 16))
        self.label_course.setTextFormat(QtCore.Qt.RichText)
        self.label_course.setObjectName("label_course")
        self.label_new = QtWidgets.QLabel(Main)
        self.label_new.setGeometry(QtCore.QRect(420, 120, 131, 16))
        self.label_new.setObjectName("label_new")
        self.button_update = QtWidgets.QPushButton(Main)
        self.button_update.setGeometry(QtCore.QRect(820, 440, 115, 25))
        self.button_update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_update.setStyleSheet("QPushButton{color: rgb(255, 255, 255)}\n"
"QPushButton{background-color: rgb(48, 112, 245)}\n"
"QPushButton:pressed{color: rgb(48, 112, 245)}\n"
"QPushButton:pressed{background-color: rgb(255, 255, 255)}\n"
"QPushButton{border-radius:10px}")
        self.button_update.setObjectName("button_update")
        self.button_update_all = QtWidgets.QPushButton(Main)
        self.button_update_all.setGeometry(QtCore.QRect(820, 480, 115, 25))
        self.button_update_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_update_all.setStyleSheet("QPushButton{color: rgb(0, 0, 0)}\n"
"QPushButton{background-color: rgb(255, 255, 255)}\n"
"QPushButton:pressed{color: rgb(255, 255, 255)}\n"
"QPushButton:pressed{background-color: rgb(48, 112, 245)}\n"
"QPushButton{border-radius:10px}\n"
"QPushButton{border-style:solid}\n"
"QPushButton{border-width:1px}\n"
"QPushButton{border-color: rgb(167, 167, 167)}")
        self.button_update_all.setObjectName("button_update_all")
        self.check_remember = QtWidgets.QCheckBox(Main)
        self.check_remember.setGeometry(QtCore.QRect(810, 170, 87, 20))
        self.check_remember.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_remember.setChecked(True)
        self.check_remember.setObjectName("check_remember")
        self.button_credit = QtWidgets.QPushButton(Main)
        self.button_credit.setGeometry(QtCore.QRect(820, 550, 115, 25))
        self.button_credit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_credit.setStyleSheet("QPushButton{color: rgb(0, 0, 0)}\n"
"QPushButton{background-color: rgb(255, 255, 255)}\n"
"QPushButton:pressed{color: rgb(255, 255, 255)}\n"
"QPushButton:pressed{background-color: rgb(48, 112, 245)}\n"
"QPushButton{border-radius:10px}\n"
"QPushButton{border-style:solid}\n"
"QPushButton{border-width:1px}\n"
"QPushButton{border-color: rgb(167, 167, 167)}")
        self.button_credit.setObjectName("button_credit")
        self.button_about = QtWidgets.QPushButton(Main)
        self.button_about.setGeometry(QtCore.QRect(810, 30, 51, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.button_about.setPalette(palette)
        self.button_about.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_about.setAutoFillBackground(False)
        self.button_about.setStyleSheet("QPushButton{color: rgb(0, 0, 0)}\n"
"QPushButton{background-color: rgb(255, 255, 255)}\n"
"QPushButton:pressed{color: rgb(255, 255, 255)}\n"
"QPushButton:pressed{background-color: rgb(48, 112, 245)}\n"
"QPushButton{border-radius:10px}\n"
"QPushButton{border-style:solid}\n"
"QPushButton{border-width:1px}\n"
"QPushButton{border-color: rgb(167, 167, 167)}")
        self.button_about.setCheckable(False)
        self.button_about.setChecked(False)
        self.button_about.setObjectName("button_about")
        self.button_reset = QtWidgets.QPushButton(Main)
        self.button_reset.setGeometry(QtCore.QRect(330, 70, 91, 32))
        self.button_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_reset.setObjectName("button_reset")

        self.retranslateUi(Main)
        self.select_term.setCurrentIndex(0)
        self.button_about.clicked.connect(Main.button_about_click)
        self.button_exit.clicked.connect(Main.button_exit_click)
        self.button_path.clicked.connect(Main.button_path_click)
        self.button_credit.clicked.connect(Main.button_credit_click)
        self.button_update.clicked.connect(Main.button_update_click)
        self.button_update_all.clicked.connect(Main.button_update_all_click)
        self.list_course.clicked['QModelIndex'].connect(Main.list_click)
        self.button_search.clicked.connect(Main.button_search_click)
        self.select_term.currentIndexChanged['QString'].connect(Main.combo_term_changed)
        self.check_all.stateChanged['int'].connect(Main.select_all_changed)
        self.button_reset.clicked.connect(Main.button_reset_click)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Ucas Course Auto Updater"))
        self.label_hello.setText(_translate("Main", "欢迎您！xxxxxx xxx"))
        self.button_exit.setText(_translate("Main", "注销"))
        self.edit_search.setPlaceholderText(_translate("Main", "课程关键字"))
        self.button_search.setText(_translate("Main", "搜索"))
        self.select_term.setItemText(0, _translate("Main", "全部学期"))
        self.select_term.setItemText(1, _translate("Main", "夏季学期"))
        self.select_term.setItemText(2, _translate("Main", "春季学期"))
        self.select_term.setItemText(3, _translate("Main", "秋季学期"))
        self.edit_path.setPlaceholderText(_translate("Main", "课件保存位置"))
        self.button_path.setText(_translate("Main", "选择路径"))
        self.check_all.setText(_translate("Main", "全选"))
        self.label_course.setText(_translate("Main", "<html><head/><body><p>已选 x 门课程，<span style=\" color:#3574f5;\">有 x 门更新：</span></p></body></html>"))
        self.label_new.setText(_translate("Main", "有更新的课件："))
        self.button_update.setText(_translate("Main", "更新 (Enter)"))
        self.button_update.setShortcut(_translate("Main", "Return"))
        self.button_update_all.setText(_translate("Main", "全部更新"))
        self.check_remember.setText(_translate("Main", "记住勾选"))
        self.button_credit.setText(_translate("Main", "学分统计"))
        self.button_about.setText(_translate("Main", "关于"))
        self.button_reset.setText(_translate("Main", "显示全部"))


import resource_rc
